name: Deploy to SFTP

on:
  push:
    branches:
      - '**' # Déclenchement sur push pour toutes les branches

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Installer les dépendances et construire le projet
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Déployer sur le SFTP de staging
      - name: Deploy to Staging SFTP
        if: github.ref != 'refs/heads/main'
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          uploads: |
            ./build/ => ./staging/

      # Déployer sur le SFTP de production
      - name: Deploy to Production SFTP
        if: github.ref == 'refs/heads/main'
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          uploads: |
            ./build/ => ./
