name: Deploy to SFTP

on:
  push:
    branches:
      - '**' # Trigger on push for all branches

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install dependencies and build the project
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Deploy to Staging SFTP
      - name: Deploy to Staging SFTP
        if: github.ref != 'refs/heads/main'
        uses: appleboy/ftp-action@v0.6.0
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: build/
          remote-dir: /www/staging/

      # Deploy to Production SFTP
      - name: Deploy to Production SFTP
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ftp-action@v0.6.0
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: build/
          remote-dir: /www/
