name: Deploy to FTP

on:
  push:
    branches:
      - '**' # Trigger on push for all branches

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install dependencies and build the project
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Deploy to Staging FTP
      - name: Deploy to Staging FTP
        if: github.ref != 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /www/staging/

      # Deploy to Production FTP
      - name: Deploy to Production FTP
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /www/
